------------------------------------ UDEMY COURSE DATA ANALYTICS -----------------------------------------------

USE portfolio_project;

-- Create a table named Udemy_Courses with all the data from the different courses appended together
SELECT * INTO Udemy_Courses
FROM(
SELECT *
FROM Business_Courses
	UNION
SELECT *
FROM Graphics_Design_Courses
	UNION
SELECT *
FROM Music_Courses
	UNION
SELECT *
FROM Web_Development_Courses) AS Udemy


SELECT *
FROM Udemy_Courses
ORDER BY Subject


-- I had to convert the Date_Published column from DATETIME Format to DATE format

SELECT Date_Published, CONVERT(Date, Date_Published)
FROM Udemy_Courses

--UPDATE Udemy_Courses
--SET Date_Published = CONVERT(Date, Date_Published)


-- I created a new column named Date_Published_Updated to house the cleaned date format

ALTER TABLE Udemy_Courses
ADD Date_Published_Updated DATE

UPDATE Udemy_Courses
SET Date_Published_Updated = CONVERT(Date, Date_Published)

-- Drop unused Date_Published Column
ALTER TABLE Udemy_Courses
DROP COLUMN Date_Published


-- I will Add an extra column to calculate Revenue generated, (Price * Number of subscribers)

ALTER TABLE Udemy_Courses
ADD Revenue float

UPDATE Udemy_Courses
SET Revenue = Price * Num_of_Subscribers

-------------------------------------------------------------------------------------------------------------------

-------------------------------------- DATA ANALYSIS AND INSIGHTS -------------------------------------------------

--------------------------------------- Queries for Card Visuals --------------------------------------------------


-- Get the count of the total number of Subjects

SELECT COUNT(DISTINCT Subject) AS Total_number_of_courses
FROM Udemy_Courses


-- Get the total number of subscribers

SELECT SUM(Num_of_Subscribers) AS Total_Subscribers
FROM Udemy_Courses

-- Get the total Revenue made

SELECT SUM(Revenue) AS Total_revenue
FROM Udemy_Courses

-- Get the total number of courses in database

SELECT COUNT(Course_Title) AS Count_of_Courses
FROM Udemy_Courses



-------------------------------------------------------------------------------------------------------------------
----------------------------------------------- Key Insights ------------------------------------------------------

-- Get the total number and percentage total of subscribers per subject

--SELECT
--	Subject,
--	SUM(Num_of_Subscribers) AS Total_subscribers_per_subject,
--	(SELECT SUM(Num_of_Subscribers) FROM Udemy_Courses) AS Total_subcribers,
--	ROUND((SUM(Num_of_Subscribers)/(SELECT SUM(Num_of_Subscribers) FROM Udemy_Courses)) * 100, 2) AS percentage_total
--FROM Udemy_Courses
--GROUP BY Subject
--ORDER BY 2 DESC


-- Get the total revenue generated per subject

SELECT 
	Subject,
	SUM(Revenue) AS Total_revenue
FROM Udemy_Courses
GROUP BY Subject
ORDER BY 2 DESC

-- Get average content duration per subject

SELECT
	Subject,
	ROUND(AVG(Content_Duration),3) AS average_content_duration
FROM Udemy_Courses
GROUP BY Subject
ORDER BY 2 DESC

-- Get the top 5 courses by revenue

SELECT TOP 5
	Course_Title,
	Subject,
	SUM(Revenue) AS Total_revenue
FROM Udemy_Courses
GROUP BY Course_Title, Subject
ORDER BY 3 DESC


-- Get number of subscribers per level of course

SELECT
	Level,
	SUM(Revenue) AS Total_revenue,
	SUM(Num_of_Subscribers) AS Number_of_subscribers
FROM Udemy_Courses
GROUP BY Level
ORDER BY 2 DESC


-- Get the Total number of courses by level 

SELECT Level, COUNT(*) AS Number_of_courses
FROM Udemy_Courses
GROUP BY Level
ORDER BY 2 DESC


-- Get number of free and paid courses

SELECT 
	Free_Paid,
	COUNT(Free_Paid) AS total_number
	FROM Udemy_Courses
GROUP BY Free_Paid
ORDER BY 2 ASC


-- Get average rating per subject
SELECT
	Subject,
	ROUND(AVG(Rating),2) AS average_rating
FROM Udemy
GROUP BY Subject
ORDER BY 2 DESC


-- Get Revenue generated by Year

SELECT Year(Date_Published_Updated) AS Year,
	   SUM(Revenue) AS Total_revenue
FROM Udemy_Courses
GROUP BY Year(Date_Published_Updated)
ORDER BY Year(Date_Published_Updated)


-- Get Revenue generated by Month

SELECT DATENAME(month, DATEADD(month, DATEPART(month, Date_Published_Updated), -1)) AS Month,
	   SUM(Revenue) AS Total_revenue
FROM Udemy_Courses
GROUP BY DATEPART(Month, Date_Published_Updated)
ORDER BY DATEPART(Month, Date_Published_Updated)


